### ISSUE TITLE
Clarify meaning of `offset`

### ISSUE THREAD

**Issue by jonahweissman** [melizalab/lab_specs#5]
In the process of explaining to Christof how this format works, I realized that the meaning of the `offset` key is a little confusing. We say:
https://github.com/melizalab/lab_specs/blob/124a511e532a6206cccce5b8c436d292ff2ec895/specs/pprox.json#L27

but it's left ambiguous whether the times in the `interval` or `stimulus.interval` keys are also relative to `offset`. I think everything probably should all be relative to offset because mixing relative with absolute times would be confusing.

**Comment by dmeliza** [comment]
I agree, everything should be relative to the start of the trial (as indicated by offset).
